-- ADMIN no longer bypasses permission checks (src/lib/permissions.ts), so
-- the one ADMIN-only capability that was checked by role name — overriding a
-- country's default currency on leads/customers — becomes a real permission,
-- granted to ADMIN (the only role that could do it before). Also refreshes
-- the catalog's module/page/action/sort order, which shifted by one.

INSERT INTO "permissions" ("name", "description", "module", "page", "action", "sort_order") VALUES
  ('view_dashboard', 'View the Dashboard home page', 'Dashboard', 'Dashboard', 'view', 0),
  ('view_verticals', 'View verticals', 'Masters', 'Verticals', 'view', 1),
  ('create_verticals', 'Create verticals', 'Masters', 'Verticals', 'create', 2),
  ('edit_verticals', 'Edit verticals', 'Masters', 'Verticals', 'edit', 3),
  ('delete_verticals', 'Delete verticals', 'Masters', 'Verticals', 'delete', 4),
  ('view_projects', 'View projects', 'Masters', 'Projects', 'view', 5),
  ('create_projects', 'Create projects', 'Masters', 'Projects', 'create', 6),
  ('edit_projects', 'Edit projects', 'Masters', 'Projects', 'edit', 7),
  ('delete_projects', 'Delete projects', 'Masters', 'Projects', 'delete', 8),
  ('view_products', 'View products', 'Masters', 'Products', 'view', 9),
  ('create_products', 'Create products', 'Masters', 'Products', 'create', 10),
  ('edit_products', 'Edit products', 'Masters', 'Products', 'edit', 11),
  ('delete_products', 'Delete products', 'Masters', 'Products', 'delete', 12),
  ('view_packages', 'View packages', 'Masters', 'Packages', 'view', 13),
  ('create_packages', 'Create packages', 'Masters', 'Packages', 'create', 14),
  ('edit_packages', 'Edit packages', 'Masters', 'Packages', 'edit', 15),
  ('delete_packages', 'Delete packages', 'Masters', 'Packages', 'delete', 16),
  ('view_lead_sources', 'View lead sources', 'Masters', 'Lead Sources', 'view', 17),
  ('create_lead_sources', 'Create lead sources', 'Masters', 'Lead Sources', 'create', 18),
  ('edit_lead_sources', 'Edit lead sources', 'Masters', 'Lead Sources', 'edit', 19),
  ('delete_lead_sources', 'Delete lead sources', 'Masters', 'Lead Sources', 'delete', 20),
  ('view_lead_status_options', 'View lead statuses', 'Masters', 'Lead Statuses', 'view', 21),
  ('create_lead_status_options', 'Create lead statuses', 'Masters', 'Lead Statuses', 'create', 22),
  ('edit_lead_status_options', 'Edit lead statuses', 'Masters', 'Lead Statuses', 'edit', 23),
  ('view_stages', 'View stages', 'Masters', 'Stages', 'view', 24),
  ('create_stages', 'Create stages', 'Masters', 'Stages', 'create', 25),
  ('edit_stages', 'Edit stages', 'Masters', 'Stages', 'edit', 26),
  ('delete_stages', 'Delete stages', 'Masters', 'Stages', 'delete', 27),
  ('view_leads', 'View leads', 'Sales', 'Leads', 'view', 28),
  ('create_leads', 'Create leads', 'Sales', 'Leads', 'create', 29),
  ('edit_leads', 'Edit leads', 'Sales', 'Leads', 'edit', 30),
  ('delete_leads', 'Delete leads', 'Sales', 'Leads', 'delete', 31),
  ('delete_nda_documents', 'Delete NDA documents on a lead', 'Sales', 'Leads', 'other', 32),
  ('override_currency', 'Override a country''s default currency on leads and customers', 'Sales', 'Leads', 'other', 33),
  ('view_lead_events', 'View lead events & documents', 'Sales', 'Lead Events & Documents', 'view', 34),
  ('create_lead_events', 'Create lead events & documents', 'Sales', 'Lead Events & Documents', 'create', 35),
  ('edit_lead_events', 'Edit lead events & documents', 'Sales', 'Lead Events & Documents', 'edit', 36),
  ('delete_lead_events', 'Delete lead events & documents', 'Sales', 'Lead Events & Documents', 'delete', 37),
  ('add_lead_discussion', 'Add discussions to lead events', 'Sales', 'Lead Events & Documents', 'other', 38),
  ('view_customers', 'View customers', 'Sales', 'Customers', 'view', 39),
  ('create_customers', 'Create customers', 'Sales', 'Customers', 'create', 40),
  ('edit_customers', 'Edit customers', 'Sales', 'Customers', 'edit', 41),
  ('delete_customers', 'Delete customers', 'Sales', 'Customers', 'delete', 42),
  ('view_companies', 'View companies', 'Sales', 'Companies', 'view', 43),
  ('create_companies', 'Create companies', 'Sales', 'Companies', 'create', 44),
  ('edit_companies', 'Edit companies', 'Sales', 'Companies', 'edit', 45),
  ('delete_companies', 'Delete companies', 'Sales', 'Companies', 'delete', 46),
  ('view_quotations', 'View quotations', 'Sales', 'Quotations', 'view', 47),
  ('create_quotations', 'Create quotations', 'Sales', 'Quotations', 'create', 48),
  ('edit_quotations', 'Edit quotations', 'Sales', 'Quotations', 'edit', 49),
  ('delete_quotations', 'Delete quotations', 'Sales', 'Quotations', 'delete', 50),
  ('export_quotations', 'Export quotations', 'Sales', 'Quotations', 'other', 51),
  ('authorize_quotation_override', 'Authorize quotation price overrides', 'Sales', 'Quotations', 'other', 52),
  ('view_demos', 'View demos', 'Sales', 'Demos', 'view', 53),
  ('create_demos', 'Create demos', 'Sales', 'Demos', 'create', 54),
  ('edit_demos', 'Edit demos', 'Sales', 'Demos', 'edit', 55),
  ('delete_demos', 'Delete demos', 'Sales', 'Demos', 'delete', 56),
  ('view_implementations', 'View implementations', 'Sales', 'Implementations', 'view', 57),
  ('create_implementations', 'Create implementations', 'Sales', 'Implementations', 'create', 58),
  ('edit_implementations', 'Edit implementations', 'Sales', 'Implementations', 'edit', 59),
  ('delete_implementations', 'Delete implementations', 'Sales', 'Implementations', 'delete', 60),
  ('view_meetings', 'View to do (meetings)', 'Meetings', 'To Do (Meetings)', 'view', 61),
  ('create_meetings', 'Create to do (meetings)', 'Meetings', 'To Do (Meetings)', 'create', 62),
  ('edit_meetings', 'Edit to do (meetings)', 'Meetings', 'To Do (Meetings)', 'edit', 63),
  ('create_mom', 'Create minutes of meeting', 'Meetings', 'Minutes of Meeting', 'create', 64),
  ('edit_mom', 'Edit minutes of meeting', 'Meetings', 'Minutes of Meeting', 'edit', 65),
  ('approve_mom', 'Approve minutes of meeting', 'Meetings', 'Minutes of Meeting', 'other', 66),
  ('publish_mom', 'Publish minutes of meeting', 'Meetings', 'Minutes of Meeting', 'other', 67),
  ('view_action_items', 'View action items', 'Meetings', 'Action Items', 'view', 68),
  ('assign_action_items', 'Create and assign action items', 'Meetings', 'Action Items', 'other', 69),
  ('manage_own_action_items', 'Update own action items', 'Meetings', 'Action Items', 'other', 70),
  ('close_action_items', 'Close action items', 'Meetings', 'Action Items', 'other', 71),
  ('verify_action_items', 'Verify action items', 'Meetings', 'Action Items', 'other', 72),
  ('reopen_action_items', 'Reopen action items', 'Meetings', 'Action Items', 'other', 73),
  ('view_meetings_dashboard', 'View the meetings dashboard', 'Meetings', 'Meetings Dashboard', 'view', 74),
  ('view_meeting_team_dashboard', 'View the team-wide meetings dashboard', 'Meetings', 'Meetings Dashboard', 'other', 75),
  ('view_meeting_reports', 'View meeting reports', 'Meetings', 'Meeting Reports', 'view', 76),
  ('export_meeting_reports', 'Export meeting reports', 'Meetings', 'Meeting Reports', 'other', 77),
  ('view_accounting', 'View the accounting dashboard', 'Finance', 'Accounting Dashboard', 'view', 78),
  ('view_invoices', 'View invoices and credit notes', 'Finance', 'Invoices', 'view', 79),
  ('create_invoices', 'Create invoices', 'Finance', 'Invoices', 'create', 80),
  ('edit_invoices', 'Edit invoices', 'Finance', 'Invoices', 'edit', 81),
  ('delete_invoices', 'Delete invoices', 'Finance', 'Invoices', 'delete', 82),
  ('create_payments', 'Create payments', 'Finance', 'Payments', 'create', 83),
  ('edit_payments', 'Edit payments', 'Finance', 'Payments', 'edit', 84),
  ('delete_payments', 'Delete payments', 'Finance', 'Payments', 'delete', 85),
  ('view_payment_reminders', 'View payment reminders', 'Finance', 'Payment Reminders', 'view', 86),
  ('create_payment_reminders', 'Create payment reminders', 'Finance', 'Payment Reminders', 'create', 87),
  ('edit_payment_reminders', 'Edit payment reminders', 'Finance', 'Payment Reminders', 'edit', 88),
  ('delete_payment_reminders', 'Delete payment reminders', 'Finance', 'Payment Reminders', 'delete', 89),
  ('view_customer_ledger', 'View the customer ledger', 'Finance', 'Customer Ledger', 'view', 90),
  ('view_accounting_reports', 'View accounting reports', 'Finance', 'Accounting Reports', 'view', 91),
  ('export_accounting', 'Export accounting data', 'Finance', 'Accounting Reports', 'other', 92),
  ('view_bills', 'View bills and suppliers', 'Finance', 'Bills', 'view', 93),
  ('create_bills', 'Create bills', 'Finance', 'Bills', 'create', 94),
  ('edit_bills', 'Edit bills', 'Finance', 'Bills', 'edit', 95),
  ('delete_bills', 'Delete bills', 'Finance', 'Bills', 'delete', 96),
  ('view_expenses', 'View expenses', 'Finance', 'Expenses', 'view', 97),
  ('create_expenses', 'Create expenses', 'Finance', 'Expenses', 'create', 98),
  ('edit_expenses', 'Edit expenses', 'Finance', 'Expenses', 'edit', 99),
  ('delete_expenses', 'Delete expenses', 'Finance', 'Expenses', 'delete', 100),
  ('view_expense_budgets', 'View expense budgets', 'Finance', 'Expense Budgets', 'view', 101),
  ('create_expense_budgets', 'Create expense budgets', 'Finance', 'Expense Budgets', 'create', 102),
  ('edit_expense_budgets', 'Edit expense budgets', 'Finance', 'Expense Budgets', 'edit', 103),
  ('delete_expense_budgets', 'Delete expense budgets', 'Finance', 'Expense Budgets', 'delete', 104),
  ('approve_expense_claims', 'Review, approve, reject and pay employee expense claims', 'Finance', 'Reimbursement Approvals', 'other', 105),
  ('view_employees', 'View employees', 'Payroll', 'Employees', 'view', 106),
  ('create_employees', 'Create employees', 'Payroll', 'Employees', 'create', 107),
  ('edit_employees', 'Edit employees', 'Payroll', 'Employees', 'edit', 108),
  ('delete_employees', 'Delete employees', 'Payroll', 'Employees', 'delete', 109),
  ('view_salary_structures', 'View salary structures', 'Payroll', 'Salary Structures', 'view', 110),
  ('create_salary_structures', 'Create salary structures', 'Payroll', 'Salary Structures', 'create', 111),
  ('edit_salary_structures', 'Edit salary structures', 'Payroll', 'Salary Structures', 'edit', 112),
  ('view_payroll', 'View payroll runs and payslips', 'Payroll', 'Payroll Runs', 'view', 113),
  ('run_payroll', 'Create, regenerate and edit payroll runs', 'Payroll', 'Payroll Runs', 'other', 114),
  ('approve_payroll', 'Approve payroll runs', 'Payroll', 'Payroll Runs', 'other', 115),
  ('view_timesheet', 'View time & attendance, leave requests and holidays', 'Payroll', 'Time & Attendance', 'view', 116),
  ('create_timesheet', 'Create time & attendance', 'Payroll', 'Time & Attendance', 'create', 117),
  ('edit_timesheet', 'Edit time & attendance', 'Payroll', 'Time & Attendance', 'edit', 118),
  ('delete_timesheet', 'Delete time & attendance', 'Payroll', 'Time & Attendance', 'delete', 119),
  ('approve_leave', 'Approve or reject leave requests', 'Payroll', 'Time & Attendance', 'other', 120),
  ('view_shifts', 'View shifts', 'Payroll', 'Shift Master', 'view', 121),
  ('create_shifts', 'Create shift master', 'Payroll', 'Shift Master', 'create', 122),
  ('edit_shifts', 'Edit shift master', 'Payroll', 'Shift Master', 'edit', 123),
  ('delete_shifts', 'Delete shift master', 'Payroll', 'Shift Master', 'delete', 124),
  ('view_loans', 'View loans & advances', 'Payroll', 'Loans & Advances', 'view', 125),
  ('create_loans', 'Create loans & advances', 'Payroll', 'Loans & Advances', 'create', 126),
  ('edit_loans', 'Edit loans & advances', 'Payroll', 'Loans & Advances', 'edit', 127),
  ('view_salary_allocation', 'View salary allocation', 'Payroll', 'Salary Allocation', 'view', 128),
  ('edit_salary_allocation', 'Edit salary allocation', 'Payroll', 'Salary Allocation', 'edit', 129),
  ('view_payroll_reports', 'View payroll reports', 'Payroll', 'Payroll Reports', 'view', 130),
  ('export_payroll', 'Export payroll data', 'Payroll', 'Payroll Reports', 'other', 131),
  ('view_statutory_settings', 'View statutory settings', 'Payroll', 'Statutory Settings', 'view', 132),
  ('create_statutory_settings', 'Create statutory settings', 'Payroll', 'Statutory Settings', 'create', 133),
  ('edit_statutory_settings', 'Edit statutory settings', 'Payroll', 'Statutory Settings', 'edit', 134),
  ('view_reports', 'View the reports hub', 'Reports', 'Reports', 'view', 135),
  ('my_space', 'My Space access', 'My Space', 'My Space', 'other', 136),
  ('my_leave', 'My Leave', 'My Space', 'My Space', 'other', 137),
  ('my_payslips', 'My Payslips', 'My Space', 'My Space', 'other', 138),
  ('view_admin_tickets', 'View admin tickets', 'Administration', 'Admin Tickets', 'view', 139),
  ('create_admin_tickets', 'Create admin tickets', 'Administration', 'Admin Tickets', 'create', 140),
  ('edit_admin_tickets', 'Edit admin tickets', 'Administration', 'Admin Tickets', 'edit', 141),
  ('view_users', 'View users', 'Administration', 'Users', 'view', 142),
  ('create_users', 'Create users', 'Administration', 'Users', 'create', 143),
  ('edit_users', 'Edit users', 'Administration', 'Users', 'edit', 144),
  ('delete_users', 'Delete users', 'Administration', 'Users', 'delete', 145),
  ('view_roles', 'View roles & permissions', 'Administration', 'Roles & Permissions', 'view', 146),
  ('create_roles', 'Create roles & permissions', 'Administration', 'Roles & Permissions', 'create', 147),
  ('edit_roles', 'Edit roles & permissions', 'Administration', 'Roles & Permissions', 'edit', 148),
  ('delete_roles', 'Delete roles & permissions', 'Administration', 'Roles & Permissions', 'delete', 149),
  ('view_audit_logs', 'View the audit report', 'Administration', 'Audit Report', 'view', 150),
  ('export_audit_logs', 'Export the audit report', 'Administration', 'Audit Report', 'other', 151),
  ('edit_settings', 'Edit company profile settings', 'Settings', 'Company Settings', 'edit', 152),
  ('create_countries', 'Create countries', 'Settings', 'Countries', 'create', 153),
  ('edit_countries', 'Edit countries', 'Settings', 'Countries', 'edit', 154),
  ('delete_countries', 'Delete countries', 'Settings', 'Countries', 'delete', 155),
  ('view_email_settings', 'View outbound email (SMTP) settings', 'Settings', 'Email Settings', 'view', 156),
  ('edit_email_settings', 'Edit email settings', 'Settings', 'Email Settings', 'edit', 157),
  ('view_notification_templates', 'View notification templates', 'Settings', 'Notification Templates', 'view', 158),
  ('edit_notification_templates', 'Edit notification templates', 'Settings', 'Notification Templates', 'edit', 159)
ON CONFLICT ("name") DO UPDATE SET "module" = EXCLUDED."module", "page" = EXCLUDED."page", "action" = EXCLUDED."action", "sort_order" = EXCLUDED."sort_order";

INSERT INTO "role_permissions" ("role_id", "permission_id")
SELECT r."id", p."id" FROM "roles" r CROSS JOIN "permissions" p
WHERE r."name" = 'ADMIN' AND p."name" = 'override_currency'
ON CONFLICT ("role_id", "permission_id") DO NOTHING;
