import prisma from '@/lib/prisma';
import dayjs from 'dayjs';
import { computeNextRunDate } from './recurrence';
import { nextAdminTicketNumber } from './ticketNumber';
import { materializeReminders } from './reminderMaterializer';
import { Frequency } from './constants';

// Nightly job: for each active recurrence due within its lead time, create
// the NEXT occurrence only (not the whole future series — a rule change
// later would otherwise mean reconciling hundreds of generated rows) by
// copying the original (parentTicketId === null) ticket for that
// recurrence, then advances nextRunDate. The (recurrenceId, dueDate)
// unique constraint on admin_tickets is the actual duplicate guard; the P2002
// catch below just makes a concurrent/duplicate run a no-op instead of a
// crash.
export async function generateDueOccurrences(now: Date = new Date()): Promise<{ generated: number }> {
  const horizon = dayjs(now);

  // leadTimeDays varies per row, so "due within lead time" is filtered in
  // JS below rather than in the WHERE clause.
  const dueRecurrences = await prisma.adminTicketRecurrence.findMany({ where: { isActive: true } });

  let generated = 0;
  for (const recurrence of dueRecurrences) {
    if (recurrence.frequency === 'CUSTOM_CRON') continue; // not yet supported — see recurrence.ts

    const generateThreshold = dayjs(recurrence.nextRunDate).subtract(recurrence.leadTimeDays, 'day');
    if (horizon.isBefore(generateThreshold)) continue;

    const templateTicket = await prisma.adminTicket.findFirst({
      where: { recurrenceId: recurrence.id, parentTicketId: null },
      orderBy: { createdAt: 'asc' },
    });
    if (!templateTicket) continue; // no original ticket to copy from yet

    let created;
    try {
      const ticketNo = await nextAdminTicketNumber(prisma);
      created = await prisma.adminTicket.create({
        data: {
          ticketNo,
          categoryId: templateTicket.categoryId,
          title: templateTicket.title,
          description: templateTicket.description,
          priority: templateTicket.priority,
          assignedToId: templateTicket.assignedToId,
          createdById: templateTicket.createdById,
          dueDate: recurrence.nextRunDate,
          recurrenceId: recurrence.id,
          parentTicketId: templateTicket.id,
          refType: templateTicket.refType,
          refId: templateTicket.refId,
        },
      });
    } catch (error: any) {
      if (error?.code === 'P2002') continue; // already generated by another run
      throw error;
    }

    await prisma.adminTicketActivity.create({
      data: { ticketId: created.id, action: 'CREATED', remarks: `Generated from recurrence #${recurrence.id}` },
    });

    const category = await prisma.adminTicketCategory.findUnique({
      where: { id: created.categoryId },
      select: { escalationRoleId: true },
    });
    await materializeReminders(created.id, created.dueDate, category?.escalationRoleId ?? null);
    generated += 1;

    const nextRun = computeNextRunDate(
      {
        frequency: recurrence.frequency as Frequency,
        intervalValue: recurrence.intervalValue,
        dayOfMonth: recurrence.dayOfMonth,
        dayOfWeek: recurrence.dayOfWeek,
        monthOfYear: recurrence.monthOfYear,
      },
      recurrence.nextRunDate
    );
    const seriesEnded = recurrence.endDate != null && dayjs(nextRun).isAfter(recurrence.endDate);
    await prisma.adminTicketRecurrence.update({
      where: { id: recurrence.id },
      data: {
        nextRunDate: nextRun,
        lastGeneratedDate: now,
        isActive: seriesEnded ? false : recurrence.isActive,
      },
    });
  }

  return { generated };
}
